- name: Installing latest docker version
  yum: name=docker state=latest
  sudo: yes

- name: Starting docker service
  service: name=docker state=started
  sudo: yes

- name: Check to see if pip is already installed
  command: "pip --version"
  ignore_errors: true
  changed_when: false
  register: pip_is_installed

- name: Get pip
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/home/ec2-user
  when: pip_is_installed.rc != 0

- name: install pip
  command: "python /home/ec2-user/get-pip.py"
  sudo: yes
  when: pip_is_installed.rc != 0

- name: delete get-pip.py
  file: state=absent path=~/get-pip.py
  when: pip_is_installed.rc != 0

- name: Installing docker-py for ansible
  pip: name=docker-py version=1.1.0 #executable=/usr/local/bin/pip
  sudo: yes

- name: Adding ec2-user to docker group
  user: name=ec2-user groups=docker append=yes
  sudo: yes

- name: Adding quay.io robot login
  copy: src=dockercfg dest=/home/ec2-user/.dockercfg owner=ec2-user
